### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by zhangrufeng** [Pistachiout/Academic-Degree-BlockChain#1]
Create channel and join error: Create channel error: error should be nil for SaveChannel of orgchannel: create channel failed: create channel failed: SendEnvelope failed: calling orderer 'orderer.example.com:7050' failed: Orderer Server Status Code: (400) BAD_REQUEST. Description: error applying config update to existing channel 'mychannel': error authorizing update: error validating ReadSet: proposed update requires that key [Group]  /Channel/Application be at version 0, but it is currently at version 1

**Comment by lyhx51** [comment]
我也是这样

**Comment by zhangrufeng** [comment]
我的解决了，进入fixtures目录，执行①doucker-compose down -v ②docker volume prune ③docker container rm -f $(docker container ls -aq)

**Comment by Pistachiout** [comment]
👍点赞

**Comment by zhangrufeng** [comment]
解决了

**Comment by lyhx51** [comment]
> 👍点赞

你好，在启动./clean_docker.sh那一步一直有一个httpconnection chunk的问题，还没运行起来，怎么解决呀

**Comment by zhangrufeng** [comment]
没有碰到这个问题

**Comment by 039203288291** [comment]
你好！
4.启动项目那一步最后的./clean_docker.sh，提示未指明参数，可能会删除所有的容器。我要继续执行吗？

![Image](https://github.com/user-attachments/assets/85ff8748-6cc6-4c32-b07d-bd100378bd31)
